repos:
-   repo: local
    hooks:
    -   id: jupyter-html
        name: HTML Render
        entry: jupyter nbconvert --to=html --template=full
        language: system
        files: .ipynb
        types: [file]
