repos:
-   repo: local
    hooks:
    -   id: jupyter-html
        name: HTML Render
        entry: jupyter nbconvert --to=html --template=full
        language: system
        files: .ipynb
        types: [file]
    -   id: jupyter-html-fix
        name: HTML Render Fix
        entry: sed -b -i 's/^None//'
        language: system
        files: .html
        types: [file]
